apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.Release_Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host:   # This will match all hosts
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.Release_Name }}-service"
                port:
                  number: 80