apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.Release_Name }}-service"
  labels:
    app: {{ .Values.Release_Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.Release_Name }}