replicaCount: 1

image:
  repository: public.ecr.aws/w1v4n0n8/java/hello-world
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi 

Release_Name: java-app
Chart_Name: hello-world